@echo off
title ChatHub Docker Environment
echo Starting containers...
docker-compose up -d

echo Running migrations...
docker-compose exec web python manage.py migrate

echo Layout check: Collecting static files...
docker-compose exec web python manage.py collectstatic --noinput

echo Showing logs (Press Ctrl+C to stop)...
docker-compose logs -f