# Generated by Django 5.2.12 on 2026-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=50, null=True),
        ),
    ]
