# Generated by Django 5.2.12 on 2026-04-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_avatar_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, default='room_avatars/room-default.png', null=True, upload_to='room_avatars/'),
        ),
    ]
