# Generated by Django 5.2.11 on 2026-03-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='private_room',
            field=models.BooleanField(default=False),
        ),
    ]
