# Generated by Django 5.2.11 on 2026-03-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_key_room_private_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='private_room',
            new_name='private',
        ),
    ]
