# Generated by Django 5.2.11 on 2026-03-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
