# Generated by Django 5.2.12 on 2026-04-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_message_expires_at_room_is_ephemeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice-message/'),
        ),
    ]
