# Generated by Django 5.2.12 on 2026-04-03 04:50

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_message_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
    ]
