# Generated by Django 5.2.12 on 2026-04-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_message_audio_file_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_file',
            field=models.FileField(blank=True, null=True, upload_to='chat-files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
