# Generated by Django 5.2.12 on 2026-04-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_message_is_file_message_is_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_file',
            new_name='message_file',
        ),
    ]
