# Generated by Django 5.2.12 on 2026-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
