# Generated by Django 5.2.12 on 2026-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_message_is_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=20, null=True),
        ),
    ]
