# Generated by Django 5.2.12 on 2026-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_room_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='current_sentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='room',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=5, null=True),
        ),
    ]
